### ISSUE TITLE
const in strict mode

### ISSUE THREAD

**Issue by cmorford** [magicdawn/node-mysql-aes#2]
I'm seeing the following error:

<application path>/node_modules/mysql-aes/index.js:7
const crypto = require('crypto')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/srv/www/oauth_service/releases/20170510192731/node_modules/middleware/node_modules/models/Configuration.js:6:9)
    at Object.<anonymous> (/srv/www/oauth_service/releases/20170510192731/node_modules/middleware/node_modules/models/Configuration.js:63:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/srv/www/oauth_service/releases/20170510192731/node_modules/middleware/node_modules/models/models.js:8:26)

**Comment by magicdawn** [comment]
Guess you are using an ancient node version. You need a higher node version, such as v4 / v6 LTS

```
magicdawn at bogon in ~
$ nvm install 0.10
######################################################################## 100.0%
Now using node v0.10.48

magicdawn at bogon in ~
$ node

magicdawn at bogon in ~
$ node -p "'use strict'; const x = 10; console.log(x)"

[eval]:1
'use strict'; const x = 10; console.log(x)
              ^^^^^
SyntaxError: Use of const in strict mode.
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:575:25)
    at startup (node.js:80:7)
    at node.js:945:3

magicdawn at bogon in ~
$ node -p "'use strict'; const x = 10; console.log(x)" --harmony
10
undefined
```

**Comment by magicdawn** [comment]
Or you can use `--harmony` node flag

**Comment by cmorford** [comment]
My apologies.  Should have checked that first.  Thanks.

**Comment by magicdawn** [comment]
Never Mind. :)
